<?php
if (function_exists("register_field_group")) {
    register_field_group(
        array(
            'id' => 'acf_council_contact',
            'title' => 'NSC Contact',
            'fields' => array(

                array(
                    'key' => 'field_100wq349o831',
                    'label' => 'Bio',
                    'name' => 'nsc_bio',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'default_value' => '',
                    'toolbar' => 'basic',
                    'media_upload' => 'no',
                ),
                array (
                    'key' => 'field_209qi118h297',
                    'label' => 'Image',
                    'name' => 'nsc_image',
                    'type' => 'image',
                    'column_width' => '',
                    'save_format' => 'object',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_601de556t404',
                    'label' => 'Surname',
                    'name' => 'nsc_surname',
                    'type' => 'text',
                    'instructions' => 'This contact\'s surname. This will determine where this contact appears alphabetically in the directory.',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_378th499a107',
                    'label' => 'Interests',
                    'name' => 'nsc_interests',
                    'type' => 'text',
                    'instructions' => 'This contact\'s interests.',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_599aw100w3672',
                    'label' => 'E-mail',
                    'name' => 'nsc_email',
                    'type' => 'text',
                    'instructions' => 'This contact\'s e-mail address.',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_598re320h8530',
                    'label' => 'LinkedIn',
                    'name' => 'nsc_linkedin',
                    'type' => 'text',
                    'instructions' => 'URL to this contact\'s LinkedIn profile.',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_298lm644e0196',
                    'label' => 'Phone Number',
                    'name' => 'nsc_phone',
                    'type' => 'text',
                    'instructions' => 'This contact\'s phone number.',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),

                array(
                    'key' => 'field_598bv209k8349',
                    'label' => 'Twitter',
                    'name' => 'nsc_twitter',
                    'type' => 'text',
                    'instructions' => 'URL to this contact\'s twitter profile.',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'nsccontact',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array(
                'position' => 'normal',
                'layout' => 'no_box',
                'hide_on_screen' => array(),
            ),
            'menu_order' => 0,
        )
    );
}