<?php
if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_site-text',
        'title' => 'Site Text',
        'fields' => array(
            array(
                'key' => 'field_529545626aad6',
                'label' => 'Site Tag Line',
                'name' => 'site_tag_line',
                'type' => 'text',
                'default_value' => 'Meet the people renewing America',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529546c06aad7',
                'label' => 'Facebook Button Expanded Text',
                'name' => 'facebook_button_expanded_text',
                'type' => 'text',
                'default_value' => 'Follow on Facebook',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529546e76aad8',
                'label' => 'Twitter Button Expanded Text',
                'name' => 'twitter_button_expanded_text',
                'type' => 'text',
                'default_value' => 'Follow on Twitter',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529547866aad9',
                'label' => 'Twitter Button Bingo Text',
                'name' => 'twitter_button_bingo_text',
                'type' => 'text',
                'default_value' => 'Tweet',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529547b26aada',
                'label' => 'Facebook Button Bingo Text',
                'name' => 'facebook_button_bingo_text',
                'type' => 'text',
                'default_value' => 'Share',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529548196aadb',
                'label' => 'Take Action Header Text',
                'name' => 'take_action_header_text',
                'type' => 'text',
                'default_value' => 'Take Action',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5295483b6aadc',
                'label' => 'More Stories Heading Prefix',
                'name' => 'more_stories_heading_prefix',
                'type' => 'text',
                'default_value' => 'More Stories in',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5295486c6aadd',
                'label' => 'Load More Button Text',
                'name' => 'load_more_button_text',
                'type' => 'text',
                'default_value' => 'Load More',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529548896aade',
                'label' => 'Nav Search Placeholder Text',
                'name' => 'nav_search_placeholder_text',
                'type' => 'text',
                'default_value' => 'Search NationSwell',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5295490b6aadf',
                'label' => 'Nav Subscribe Placeholder Text',
                'name' => 'nav_subscribe_placeholder_text',
                'type' => 'text',
                'default_value' => 'Subscribe to NationSwell daily',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529549396aae0',
                'label' => 'Byline Prefix Text',
                'name' => 'byline_prefix_text',
                'type' => 'text',
                'default_value' => 'by',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_529564594a5f8',
                'label' => 'Category Prefix Text',
                'name' => 'category_prefix_text',
                'type' => 'text',
                'default_value' => 'Appears in',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_52961cee8ec9a',
                'label' => 'Take Action Privacy Policy Text',
                'name' => 'take_action_privacy_policy_text',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_67828flw4vt3p',
                'label' => 'Tweet Your Rep Privacy Policy Text',
                'name' => 'tweet_rep_privacy_policy_text',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_52a8852ab8f1a',
                'label' => 'Share Take Action Text',
                'name' => 'share_take_action_text',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_52a50c0b78347',
                'label' => 'Share Take Action Button Text',
                'name' => 'share_take_action_button_text',
                'type' => 'text',
                'default_value' => 'Spread The Word',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_52961e1b1d13c',
                'label' => 'Main Menu Header',
                'name' => 'main_menu_header',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_52962d5175193',
                'label' => 'Take Action Thanks Header',
                'name' => 'take_action_thanks_header',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_52962dad75194',
                'label' => 'Take Action Thanks Text',
                'name' => 'take_action_thanks_text',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_52962dc275195',
                'label' => 'Take Action Thanks Subscribe Text',
                'name' => 'take_action_thanks_subscribe_text',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_49710fe926487',
                'label' => 'Embedded Newsletter Subscribe Widget Copy',
                'name' => 'embedded_subscribe_copy',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_19925pw466103',
                'label' => 'Embedded Newsletter Subscribe Widget Button Text',
                'name' => 'embedded_subscribe_button_text',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_48533yi074431',
                'label' => 'Call to Action Button Text',
                'name' => 'cta_button_text',
                'type' => 'text',
                'default_value' => 'Discover More Ways to Move America Forward',
                'placeholder' => 'Discover More Ways to Move America Forward',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
}
